[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  base = "hmda-explorer/"
  command = "yarn build"
  publish = "build"
